# 1. Introduction to Numpy

In [1]:
import numpy as np

In [2]:
lst = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
lst

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
lst.ndim

2

In [4]:
lst.shape

(2, 4)

In [5]:
lst.size

8

In [6]:
lst.dtype

dtype('int32')

In [7]:
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 2. Reshape and Random

In [9]:
np.random.random((2, 4))

array([[0.0053573 , 0.02288375, 0.32532449, 0.36081326],
       [0.22836095, 0.10517946, 0.57551713, 0.07091545]])

In [10]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
lst

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.reshape(lst, (2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
lst.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# 3. Arith. Ops.

In [15]:
lst *= lst
lst

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [16]:
lst.min()

1

In [17]:
lst.max()

64

# 4. Arith. on Multiple Arrays

In [18]:
lst + lst/2

array([[ 1.5,  6. , 13.5, 24. ],
       [37.5, 54. , 73.5, 96. ]])

# 5. Sorting

In [19]:
np.sort(lst, kind = 'mergesort')

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

# 6. Merging

In [20]:
np.vstack((lst/2, lst))

array([[ 0.5,  2. ,  4.5,  8. ],
       [12.5, 18. , 24.5, 32. ],
       [ 1. ,  4. ,  9. , 16. ],
       [25. , 36. , 49. , 64. ]])

In [21]:
np.hstack((lst, lst/2))

array([[ 1. ,  4. ,  9. , 16. ,  0.5,  2. ,  4.5,  8. ],
       [25. , 36. , 49. , 64. , 12.5, 18. , 24.5, 32. ]])

In [22]:
one = np.concatenate((lst/2, lst), axis = 1)
one.shape

(2, 8)

In [23]:
two = np.concatenate((lst/2, lst), axis = 0)
two.shape

(4, 4)

In [24]:
np.hsplit(lst, 2)

[array([[ 1,  4],
        [25, 36]]),
 array([[ 9, 16],
        [49, 64]])]

In [25]:
np.vsplit(lst, 2)

[array([[ 1,  4,  9, 16]]), array([[25, 36, 49, 64]])]

# 7. DAP

Similar to python slicing

# 8. Automation using NumPy

In [29]:
lst[lst % 2 == 0]

array([ 4, 16, 36, 64])