# 1. Introduction to Numpy

In [2]:
import numpy as np

In [3]:
lst = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
lst

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
lst.ndim

2

In [5]:
lst.shape

(2, 4)

In [6]:
lst.size

8

In [7]:
lst.dtype

dtype('int32')

In [8]:
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 2. Reshape and Random

In [10]:
np.random.random((2, 4))

array([[0.31037359, 0.4243986 , 0.07060176, 0.16232785],
       [0.80809492, 0.0022729 , 0.7133301 , 0.01879591]])

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
lst

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
np.reshape(lst, (2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
lst.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# 3. Arith. Ops.

In [16]:
lst *= lst
lst

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [17]:
lst.min()

1

In [18]:
lst.max()

64

# 4. Arith. on Multiple Arrays

In [19]:
lst + lst/2

array([[ 1.5,  6. , 13.5, 24. ],
       [37.5, 54. , 73.5, 96. ]])

# 5. Sorting

In [20]:
np.sort(lst, kind = 'mergesort')

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

# 6. Merging

In [21]:
np.vstack((lst/2, lst))

array([[ 0.5,  2. ,  4.5,  8. ],
       [12.5, 18. , 24.5, 32. ],
       [ 1. ,  4. ,  9. , 16. ],
       [25. , 36. , 49. , 64. ]])

In [22]:
np.hstack((lst, lst/2))

array([[ 1. ,  4. ,  9. , 16. ,  0.5,  2. ,  4.5,  8. ],
       [25. , 36. , 49. , 64. , 12.5, 18. , 24.5, 32. ]])

In [23]:
one = np.concatenate((lst/2, lst), axis = 1)
one.shape

(2, 8)

In [24]:
two = np.concatenate((lst/2, lst), axis = 0)
two.shape

(4, 4)

In [25]:
np.hsplit(lst, 2)

[array([[ 1,  4],
        [25, 36]]),
 array([[ 9, 16],
        [49, 64]])]

In [26]:
np.vsplit(lst, 2)

[array([[ 1,  4,  9, 16]]), array([[25, 36, 49, 64]])]

# 7. DAP

Similar to python slicing

# 8. Automation using NumPy

In [27]:
lst[lst % 2 == 0]

array([ 4, 16, 36, 64])

# Quiz

In [34]:
lst.dtype

dtype('int32')

In [37]:
list(lst)

[array([ 1,  4,  9, 16]), array([25, 36, 49, 64])]

In [41]:
np.full(shape= (2, 4), fill_value = 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [42]:
np.array([6, 7, 5, 8]).dot(np.array([4, 3, 7, 8]))

144

In [46]:
np.flipud(lst)

array([[25, 36, 49, 64],
       [ 1,  4,  9, 16]])

In [53]:
np.sort(lst)[::-1]

array([[25, 36, 49, 64],
       [ 1,  4,  9, 16]])

In [54]:
array_1 = [1, 2, 3, 5, 4, 6, 7, 8, 5, 3, 2]
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


In [56]:
array_1[1::2]

[2, 5, 6, 8, 3]

In [58]:
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])
array_new = np.stack((array_1, array_2), axis = 0)
array_new

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [61]:
array1 = np.array([[1, 2, 3, 4, 5], [20, 30, 40, 50, 60]])
array2 = np.array([[6, 7, 8, 9, 10], [9, 8, 7, 6, 5]])

array1 = np.column_stack([array1, array2])
array1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [20, 30, 40, 50, 60,  9,  8,  7,  6,  5]])

# Pandas

In [62]:
import pandas as pd

C:\Users\rishi\AppData\Local\Temp\ipykernel_28160\4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [70]:
Data = pd.DataFrame([[1, 2, 3, 4, 5], [8]])
Data

0    1    2    3    4
0  1  2.0  3.0  4.0  5.0
1  8  NaN  NaN  NaN  NaN