In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
import time

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"Vectorized time: {str(1000*(toc-tic))}ms")

Vectorized time: 0.9443759918212891ms


In [5]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(f"Non Vectorized: {str(1000*(toc-tic))}ms")

Non Vectorized: 496.17862701416016ms


Hence Vectorisation does a lot good 👍

## Vectorizing Examples

Avoid explicit for loops !

### Logistic Regression

In [6]:
# x[:][0] is one training set, x[:][1] begin other, x[0], x[1], x[2] are different features
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 0, 1])

In [7]:
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")

x.shape = (3, 3)
y.shape = (3,)


Since one of our training example is a three dimensional vector, our weights vector will be a 1*3 dimensional vector, and bias 'b' will be a one dimensional vector or a scalar

In [8]:
w = np.random.rand(3)
b = np.random.rand(1)

In [9]:
print(f"w.shape = {w.shape}")
print(f"b.shape = {b.shape}")

w.shape = (3,)
b.shape = (1,)


Calculating the function $f(x)$ given by,
$$f_{\vec{w}, b}(\vec{x}) = \vec{w}^{T} \cdot \vec{x} + b$$

In [10]:
f = np.transpose(w) @ x + b
f

array([10.28446072, 12.78829606, 15.2921314 ])

Calculating $\hat{y}$
$$\hat{y} = \sigma(f_{\vec{w}, b}(\vec{x}))$$ \
$$\hat{y} = \frac{1}{1+e^{-(f_{\vec{w}, b}(\vec{x}))}}$$

In [11]:
y_pred = 1/(1+np.exp(f))
y_pred

array([3.41586443e-05, 2.79326652e-06, 2.28408161e-07])

Calculating the cost
$$J(\vec{w}, b) = \frac{1}{m} \sum_{i=1}^{m}\big[ -y*log(\hat{y}) - (1-y)*log(1-\hat{y}) \big]$$

In [12]:
Loss = -(y*np.log(y_pred)) - ((1-y)*np.log(1-y_pred))
Loss

array([1.02844949e+01, 2.79327042e-06, 1.52921316e+01])

In [13]:
Cost = np.sum(Loss)/Loss.shape[0]
Cost

8.525543099605764

Now, for gradient descent
$$d\vec{z} = \hat{y} - \vec{y}$$

In [14]:
dz = y_pred - y
dz

array([-9.99965841e-01,  2.79326652e-06, -9.99999772e-01])

Update
$$d\vec{w} = \frac{d\vec{x} \cdot d\vec{z}^{T}}{m}$$ \
$$d\vec{b} = \frac{1}{m}\sum_{i=1}^{m}dz^{(i)}$$

In [15]:
dw = np.dot(x, np.transpose(dz))/dz.shape[0]
db = np.sum(dz)/dz.shape[0]

### Broadcasting