In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
import time

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"Vectorized time: {str(1000*(toc-tic))}ms")

Vectorized time: 1.027822494506836ms


In [5]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(f"Non Vectorized: {str(1000*(toc-tic))}ms")

Non Vectorized: 872.2748756408691ms


Hence Vectorisation does a lot good 👍

## Vectorizing Examples

Avoid explicit for loops !

### Logistic Regression

In [6]:
# x[:][0] is one training set, x[:][1] begin other, x[0], x[1], x[2] are different features
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 0, 1])

In [7]:
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")

x.shape = (3, 3)
y.shape = (3,)


Since one of our training example is a three dimensional vector, our weights vector will be a 1*3 dimensional vector, and bias 'b' will be a one dimensional vector or a scalar

In [8]:
w = np.random.rand(3)
b = np.random.rand(1)

In [9]:
print(f"w.shape = {w.shape}")
print(f"b.shape = {b.shape}")

w.shape = (3,)
b.shape = (1,)


Calculating the function $f(x)$ given by,
$$f_{\vec{w}, b}(\vec{x}) = \vec{w}^{T} \cdot \vec{x} + b$$

In [10]:
f = np.transpose(w) @ x + b
f

array([4.74218496, 6.02756978, 7.3129546 ])

Calculating $\hat{y}$
$$\hat{y} = \sigma(f_{\vec{w}, b}(\vec{x}))$$ \
$$\hat{y} = \frac{1}{1+e^{-(f_{\vec{w}, b}(\vec{x}))}}$$

In [11]:
y_pred = 1/(1+np.exp(f))
y_pred

array([0.0086442 , 0.00240555, 0.0006664 ])

Calculating the cost
$$J(\vec{w}, b) = \frac{1}{m} \sum_{i=1}^{m}\big[ -y*log(\hat{y}) - (1-y)*log(1-\hat{y}) \big]$$

In [12]:
Loss = -(y*np.log(y_pred)) - ((1-y)*np.log(1-y_pred))
Loss

array([4.75086674e+00, 2.40844433e-03, 7.31362122e+00])

In [13]:
Cost = np.sum(Loss)/Loss.shape[0]
Cost

4.022298801565044